title       = "exchangerate"
baseURL     = "https://exchangerate-cli.tamnd.com/"
description = "A command line for exchangerate."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/exchangerate-cli"
